### ISSUE TITLE
new operator: is + AND or is all

### ISSUE THREAD

**Issue by tainewoo** [HugoHasenbein/redmine_more_filters#2]
Currently the operator of issue filter "is" actually acts as "is + OR", if there are multiple values selected after the operator "is", the logical connection between different values is "OR", so just like "is any of the values".
But if we want to filter the issues, using is xxx AND xxx AND xxx...., it's not working, because the filter set only support one instance for one filter.
Such as, filter Affected version can only be added for one time, with one operator and one value.

it would be good if you can help implement this kind of operator.

**Comment by HugoHasenbein** [comment]
Dear Taine,

thank you for your feedback. I'll have a look at that issue.

I was trying to reproduce, what you have written.


If use the "is" filter for issues, lets say

Issue "is": 70,71,72

and I add the filter

Subject "begins contains any of": foo bar

Then I get the following base scope

issues.id IN (70,71,72) AND (issues.subject LIKE '%foo%' OR issues.subject LIKE '%bar%')


If I use the "is" filter for issues, lets say

Issue "is": 70,71,72

and I add the filter

Subject "begins contains all of": foo bar

Then I get the following base scope

issues.id IN (70,71,72) AND (issues.subject LIKE '%foo%' AND issues.subject LIKE '%bar%')

So, currently I cannot reproduce an error or see an error. Maybe I have not understood your issue report.

Could you reply with the filters you add (Issue "is" and Subject "contains...") and write a pseudo SQL-statement like above? With both I may understand better what the issue is (or where the logic error is)

Thank you for your feedback again

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,
Thank you for your reply.
I mean, i add the filter for a field with multiple value allowed, format as list or key/value list, for example "OS".
And i set the operator as "is", value as "OS1.id,OS2.id".
Then normally the SQL would be: issue.OS IN (OS1.id,OS2.id).
But if i need to search the issues which the OS has value both OS1 and OS2, the SQL should be:
issue.OS IN (OS1.id) AND issue.OS in (OS2.id)

**Comment by HugoHasenbein** [comment]
Dear Taine,

the redmine_more_filters plugin adds filters for strings and dates. it will leave the filters for integers (id) alone.

The (untouched) integer filters are strictly OR-related. This makes sense as an integer cannot possibly be one number and at the same time be another number.

Unless I heavily misunderstand, I think I cannot help. If I DO misunderstand, then please advise / clarify.

Best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

Thank you for you reply.

https://www.redmine.org/projects/redmine/wiki/RedmineCustomFields#Lists-and-KeyValues-list

There is a  format of custom field in Redmine as Key/Value list. It's kind of enumeration. Every value of this kind of fields has a key-value pair.
Such as, value of field product:

|_.id |_.value |
|1    |pd1      |
|2    |pd2      |

For this kind of fields, Redmine will treat it as enumeration, so the operator for them will be: is/not. and for the is, the relation of the values would be OR.

And, actually the field can have multiple values. Such as, issue1 affects both pd1 and pd2. So the value of field product of issue1 is pd1 AND pd2.
But they should be stored using the id, so the value of field product of issue1 is 1 AND 2.

in this case, we may need to filter the issues, which not only affect pd1, or only affect pd2.
If we need to filter the issues, which affects both pd1 and pd2. We need the AND relation of the ids.

**Comment by HugoHasenbein** [comment]
Dear Taine,

I. Issue

I have eventually understood your issue, which indeed is a bug or an issue in Redmine, needing some attention.


II. The redmine_more_filters plugin

The redmine_more_filters plugin does only patch the filters for

:text

and

:date


The redmine_more_filters plugin does not patch the filters for

:list_optional

which are used for the multiple values field#value custom field.

The multiple values field#value custom field must be the custom fields you use.


III. Redmine under the hood

I have taken a close look, what happens in Redmine.

The multiple values field#value custom field actually stores one custom field row for each value.

So if you store 'pd1', 'pd2', 'pd3' for the multiple value custom filed, then actually three custom_values are created

a. The "is" -filter

The

"is" filter eventually creates a sub-sql resulting in

"custom_values.value IN ('…', '…', '…'………),

where '…' stands for all the values.

The SQL IN-clause is indeed an OR-clause. The SQL IN-clause is not an AND-clause

This filter selects those, where the value is one of any in the list

b. The "is not" -filter

The

"is" filter eventually creates a sub-sql resulting in

"custom_values.value IS NULL OR custom_values.value NOT IN ('…', '…', '…'………),

where '…' stands for all the values.

This selects empty values and those, which are not in the list

c. The "any" -filter

The

"any" filter  eventually creates a sub-sql resulting in

"custom_values.value IS NOT NULL AND custom_values.value <> ''

It results in any existing value

d. The blank-filter

The eventually creates a sub-sql resulting in

"custom_values.value IS NULL OR custom_values.value = ''

It results in any empty value


e. wrong filter denomination

So the filter denomination of redmine for this field seems to be wrong

The "is" filter (a.) should be named "is any of".

The "is not" filter (b.) should be named "empty or none of"

The "any" filter (c.) should be named "any of"

The "blank" filter (d.) is named correctly

There is currently no AND filter, which could be named "all of".


IV. Further steps

The filters in redmine are created in several levels. When it comes to selecting the filters, then the join table between issues and custom_fields is already done.

The "is" filter should create something like

"EXISTS( SELECT DISTINCT issue.id <http://issue.id/> from issues LEFT OUTER JOIN custom_values.value ON custom_value.customized_id = issues.id <http://issues.id/> AND custom_value.customized_type = 'Issue' AND custom_field.id <http://custom_field.id/> = <CUSTOM_FIELD_ID> WHERE custom_values.value = <VALUE1>)

AND

"EXISTS( SELECT DISTINCT issue.id <http://issue.id/> from issues LEFT OUTER JOIN custom_values.value ON custom_value.customized_id = issues.id <http://issues.id/> AND custom_value.customized_type = 'Issue' AND custom_field.id <http://custom_field.id/> = <CUSTOM_FIELD_ID> WHERE custom_values.value = <VALUE2>)

[…]

AND

"EXISTS( SELECT DISTINCT issue.id <http://issue.id/> from issues LEFT OUTER JOIN custom_values.value ON custom_value.customized_id = issues.id <http://issues.id/> AND custom_value.customized_type = 'Issue' AND custom_field.id <http://custom_field.id/> = <CUSTOM_FIELD_ID> WHERE custom_values.value = <VALUEn>)


This seems like an overcomplicated SQL-

Let me think how to solve that issue

best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

Yes you are right, the behavior of the operator for key/value list and also other enumeration with multiple value allowed, currently is "xxx of" insteadly, so actually if we need to filter them using as "all of", there is not operator for it.

Thank you for your detail information, if this "is all of" operator can be implemented, it will be very very useful.

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

there is another solution to work around:
add support to add multiple instance for a single filter.
Such as:
If i want to filter issues with filter of a multiple value allowed field, named "OS", it contains some of predefined values such as OS1, OS2, OS3...
If i want to filter issues has value OS1 AND OS2, with the feature, I can:
1. first add Filter "OS", operator "IS", value "OS1".
2. then add FIlter "OS" again, operator "IS", value "OS2".
And apply.

**Comment by tainewoo** [comment]
This will be useful for lots of usage.
Such as IS OS1 and IS NOT OS2
Contains string1 and not contains string2
...
sounds great.

**Comment by HugoHasenbein** [comment]
Dear Taine,

your idea makes sense - I'll have a look at it.

Best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein 

thank you so much, i am looking forward to that, thank you for your great plugin
