### ISSUE TITLE
Asigned To Not Equal issue

### ISSUE THREAD

**Issue by smlabonia** [HugoHasenbein/redmine_more_filters#20]
Hi Hugo, nice to talk with you.

First of all, thanks for the plugin.

I have two issues, the second is more important than first.

First:

When i try to filter by assigned_to, equal option, i have to make a trick to can add more users. I dont know why, need to unselect, re select and something like that to make it works. But finally is ok.

Second:

If i want to filter by assigned_to, not equal option, i have no field to select users to filter, not at all.

![image](https://user-images.githubusercontent.com/28115014/80897767-d0a95300-8cd2-11ea-9864-a5c3977632b3.png)

**Comment by HugoHasenbein** [comment]
Dear ...,

I was trying to reproduce your error. Unfortunately - or good - my version here works fine.
Maybe you open the javascript console on your browser (Safari / Chrome / Firefox: right-click and show element options) and see if there are some error messages?

Best regards

Stepahn
