### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain'

### ISSUE THREAD

**Issue by tainewoo** [HugoHasenbein/redmine_more_filters#4]
with redmine4, there would be error, because alias_method_chain is not available after rails3.

NoMethodError: undefined method `alias_method_chain' 

http://railscasts.com/episodes/232-routing-walkthrough-part-2?view=asciicast

"This technique is used often in the Rails 3 source code. Earlier versions of Rails used alias_method_chain to override specific behaviour, but now in Rails 3 we can just use super."

**Comment by HugoHasenbein** [comment]
Dear TAINE

I'm sorry to say, that the plugin currently does not support redmine 4.

Your feature request is a very interesting one, but currently i do not see how to solve that issue, as your feature request redmine would require a complete different SQL statement within the core redmine. I am thinking of how to implement the filter.

Please bear in mind that the current filter mechanism works on one field per filter only. The (current) filter mechanism does not allow to search for elements having a plurality of linked elements, which is the case for this particular custom field.

let me think about your issue - currently I am tied up in work. In between xmas and ew year is a good time to think and sit on code

best regards

Stephan

**Comment by tainewoo** [comment]
https://github.com/HugoHasenbein/redmine_more_filters/pull/5

Hi  @HugoHasenbein 
Thank you for your great plugin.
This PR fixes this issue. And I tested it with Redmine4, but i dont have Redmine3.x environment.
You can review.

**Comment by tainewoo** [comment]
PR https://github.com/HugoHasenbein/redmine_more_filters/pull/9 can fix this issue with rails3+/redmine4+
