### ISSUE TITLE
feature: option to set the relation (AND?OR?brackets?) between different filers enabled for the query

### ISSUE THREAD

**Issue by tainewoo** [HugoHasenbein/redmine_more_filters#8]
Currently the default relationship between all filters enabled in Issue Query is "AND".
But this kind of filter is not powerful enough.

If there is option to choose relationship for each new added filter, and option to set the brackets to combine them into different parts, that would be much more flexible for use.

**Comment by HugoHasenbein** [comment]
Dear Taine,

Please try this version of redmine_more_filters (version 1.2.0).

For an Object (Issue), which has a custom value of type "Key/Value" List with "multiple" option activated, the following will be true:

Issue's custom field is "a, b" out of possible values "a, b, c, d", then the following will match

Filter: is "a"
Filter: is "b"
Filter: is "a", "b"

Filter will not match

Filter: is "c"
Filter: is "a", "b", "c"
Filter: is "c"

Filter will match:

Filter: is not "c"
Filter: is not "d"
Filter: in not "c", "d"

Currently, it is not supported to have the following

Filter: is "a", "b" ("c" and "d" is unselected) to match in a sense like ("a" AND "b") AND NOT ("c" and "d")

Filter: is "a" to not match Issue with custom field "a", "b"

Let me know, if this suffices. Else, I will look into the matter, if it is possible to add the same filter more than once, which could be very tricky to work.

Best regards

Stephan (Hugo Hasenbein)

**Comment by HugoHasenbein** [comment]
Dear Taine,

this version 1.2.1 is strict

Filter: is "a" will not match a,b
Filter: is "a, b" will only match a,b

Filter: is not "a" will match a,b
Filter: is not "a, b" will not match a,b

Tell me, if this filter helps you

Best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein 

Thank you for such a great news.
And one more question, do you mean you added a new operator for the strict "is" or just override the original operator "is"? maybe it would be better to keep the original one, and add a new one for the strict "is".

And where can i get the new version of this plugin? because i didn't find the new commit from this repository.

**Comment by HugoHasenbein** [comment]
Dear Taine,

I am currently creating a new commit with "is" being eseentially "OR", "is(strict)" being essentially "AND" and so forth. I'll try to add the new feature not only for custom fields. Hang on, you'll receive a notice shortly

Best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein 

Got it, i will wait for this new feature and test it, thank you so much.

**Comment by HugoHasenbein** [comment]
Dear Taine,

new release is published. Works specifically on ListCustomFields and Date/Value CustomFields

Best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

Got it, i will download and test it right now, thank you so much.

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

I tested it, the is (strict) and is not (strict) works well, thank you for your great help.

And currently the situation is:

Issue1: CFMultiValue value: "a"
Issue2: CFMultiValue value: "a","b"
Issue3: CFMultiValue value: "a","b","c"

Query and Result:
Filter CFMultiValue, Operator is, Value "b", Result: Issue1+Issue2+Issue3
Filter CFMultiValue, Operator is (strict), Value "a", Result: Issue1
Filter CFMultiValue, Operator is (strict), Value "a","b", Result: Issue2

So the last thing is, kind of "has (strict)", or maybe named as "is (at least)".
Filter CFMultiValue, Operator has (strict), Value "a","b", Result: Issue2+Issue3.
Is this doable?

**Comment by tainewoo** [comment]
and also the has not (strict) : is not "a" and is not "b"

----update: currently the "is not" should be already: is not (a | b), so please ignore it.
Maybe if needed, should be has not (strict: is not ( a && b), which match ab, abc, abcd... but will not match a, ac, acd...

**Comment by HugoHasenbein** [comment]
Dear Taine,

please look up Version 1.2.3 supporting these filters, too.

Best regards

Stephan

**Comment by tainewoo** [comment]
Hi @HugoHasenbein ,

v1.2.3 it's tested perfect, thank you for your help.
